name: Bug Report
description: Report a bug or unexpected behavior in objutils
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to..., I expect... but instead...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of objutils is affected?
      options:
        - Hex file readers/writers (ihex, srec, titxt, ...)
        - ELF / DWARF
        - PE/COFF / PDB
        - Registry / High-level API
        - CLI / Scripts
        - Installation / Build
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Format / Module (if applicable)
      description: Which file format or module is involved?
      options:
        - Intel HEX (ihex)
        - Motorola S-Record (srec)
        - TI-TXT (titxt)
        - ELF / DWARF
        - PE/COFF
        - PDB
        - Other / Unknown
    validations:
      required: false

  - type: input
    id: objutils-version
    attributes:
      label: objutils Version
      description: Which version of objutils are you using?
      placeholder: "e.g., 1.0.0 or 'installed from git main branch'"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      placeholder: "e.g., 3.12.1"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running on?
      options:
        - Windows 10
        - Windows 11
        - Ubuntu / Debian
        - Other Linux
        - macOS
        - Other
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install objutils?
      options:
        - pip install objutils
        - poetry install
        - Built from source (pip install .)
        - Built from source (python build_ext.py)
        - Other
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Create config with...
        2. Run the following code...
        3. See error...
      value: |
        ```python
        # Your minimal reproducible example here
        import objutils

        img = objutils.load("ihex", "input.hex")
        objutils.dump("srec", "output.srec", img)
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include full error messages and stack traces.
      placeholder: |
        ERROR:objutils:...
        Traceback (most recent call last):
          ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional Logs
      description: Any additional logs, debug output, or context
      placeholder: Use flag for verbose output if applicable
      render: text

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have tested with the latest version of pyxcp
          required: false
        - label: I can provide a minimal reproducible example
          required: false
