PE_SIGNATURE = b"PE\x00\x00"

# Optional header magic
OPTIONAL_HDR_MAGIC_PE32 = 0x10B
OPTIONAL_HDR_MAGIC_PE32_PLUS = 0x20B

IMAGE_FILE_MACHINE_UNKNOWN = 0x0  # The content of this field is assumed to be applicable to any machine type
IMAGE_FILE_MACHINE_ALPHA = 0x184  # Alpha AXP, 32-bit address space
IMAGE_FILE_MACHINE_ALPHA64 = 0x284  # Alpha 64, 64-bit address space
IMAGE_FILE_MACHINE_AM33 = 0x1D3  # Matsushita AM33
IMAGE_FILE_MACHINE_AMD64 = 0x8664  # x64
IMAGE_FILE_MACHINE_ARM = 0x01C0  # ARM little endian
IMAGE_FILE_MACHINE_ARM64 = 0xAA64  # ARM64 little endian
IMAGE_FILE_MACHINE_ARM64EC = 0xA641  # ABI that enables interoperability between native ARM64 and emulated x64 code.
IMAGE_FILE_MACHINE_ARM64X = 0xA64E  # Binary format that allows both native ARM64 and ARM64EC code to coexist in the same file.
IMAGE_FILE_MACHINE_ARMNT = 0x01C4  # ARM Thumb-2 little endian
IMAGE_FILE_MACHINE_AXP64 = 0x284  # AXP 64 (Same as Alpha 64)
IMAGE_FILE_MACHINE_EBC = 0xEBC  # EFI byte code
IMAGE_FILE_MACHINE_I386 = 0x014C  # Intel 386 or later processors and compatible processors
IMAGE_FILE_MACHINE_IA64 = 0x200  # Intel Itanium processor family
IMAGE_FILE_MACHINE_LOONGARCH32 = 0x6232  # LoongArch 32-bit processor family
IMAGE_FILE_MACHINE_LOONGARCH64 = 0x6264  # LoongArch 64-bit processor family
IMAGE_FILE_MACHINE_M32R = 0x9041  # Mitsubishi M32R little endian
IMAGE_FILE_MACHINE_MIPS16 = 0x266  # MIPS16

# COFF Header Characteristics
IMAGE_FILE_RELOCS_STRIPPED = 0x0001
IMAGE_FILE_EXECUTABLE_IMAGE = 0x0002
IMAGE_FILE_LINE_NUMS_STRIPPED = 0x0004
IMAGE_FILE_LOCAL_SYMS_STRIPPED = 0x0008
IMAGE_FILE_AGGRESSIVE_WS_TRIM = 0x0010
IMAGE_FILE_LARGE_ADDRESS_AWARE = 0x0020
IMAGE_FILE_BYTES_REVERSED_LO = 0x0080
IMAGE_FILE_32BIT_MACHINE = 0x0100
IMAGE_FILE_DEBUG_STRIPPED = 0x0200
IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x0400
IMAGE_FILE_NET_RUN_FROM_SWAP = 0x0800
IMAGE_FILE_SYSTEM = 0x1000
IMAGE_FILE_DLL = 0x2000
IMAGE_FILE_UP_SYSTEM_ONLY = 0x4000
IMAGE_FILE_BYTES_REVERSED_HI = 0x8000

# Section characteristics (subset)
IMAGE_SCN_CNT_CODE = 0x00000020
IMAGE_SCN_CNT_INITIALIZED_DATA = 0x00000040
IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080
IMAGE_SCN_MEM_EXECUTE = 0x20000000
IMAGE_SCN_MEM_READ = 0x40000000
IMAGE_SCN_MEM_WRITE = 0x80000000

# Storage classes (subset)
IMAGE_SYM_CLASS_EXTERNAL = 2
IMAGE_SYM_CLASS_STATIC = 3


def decode_characteristics(characteristics: int) -> list[str]:
    """Decodes the COFF header characteristics flags."""
    flags = []
    if characteristics & IMAGE_FILE_RELOCS_STRIPPED:
        flags.append("RELOCS_STRIPPED")
    if characteristics & IMAGE_FILE_EXECUTABLE_IMAGE:
        flags.append("EXECUTABLE_IMAGE")
    if characteristics & IMAGE_FILE_LINE_NUMS_STRIPPED:
        flags.append("LINE_NUMS_STRIPPED")
    if characteristics & IMAGE_FILE_LOCAL_SYMS_STRIPPED:
        flags.append("LOCAL_SYMS_STRIPPED")
    if characteristics & IMAGE_FILE_AGGRESSIVE_WS_TRIM:
        flags.append("AGGRESSIVE_WS_TRIM")
    if characteristics & IMAGE_FILE_LARGE_ADDRESS_AWARE:
        flags.append("LARGE_ADDRESS_AWARE")
    if characteristics & IMAGE_FILE_BYTES_REVERSED_LO:
        flags.append("BYTES_REVERSED_LO")
    if characteristics & IMAGE_FILE_32BIT_MACHINE:
        flags.append("32BIT_MACHINE")
    if characteristics & IMAGE_FILE_DEBUG_STRIPPED:
        flags.append("DEBUG_STRIPPED")
    if characteristics & IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP:
        flags.append("REMOVABLE_RUN_FROM_SWAP")
    if characteristics & IMAGE_FILE_NET_RUN_FROM_SWAP:
        flags.append("NET_RUN_FROM_SWAP")
    if characteristics & IMAGE_FILE_SYSTEM:
        flags.append("SYSTEM")
    if characteristics & IMAGE_FILE_DLL:
        flags.append("DLL")
    if characteristics & IMAGE_FILE_UP_SYSTEM_ONLY:
        flags.append("UP_SYSTEM_ONLY")
    if characteristics & IMAGE_FILE_BYTES_REVERSED_HI:
        flags.append("BYTES_REVERSED_HI")
    return flags


__all__ = [
    "PE_SIGNATURE",
    "OPTIONAL_HDR_MAGIC_PE32",
    "OPTIONAL_HDR_MAGIC_PE32_PLUS",
    "IMAGE_FILE_MACHINE_UNKNOWN",
    "IMAGE_FILE_MACHINE_ALPHA",
    "IMAGE_FILE_MACHINE_ALPHA64",
    "IMAGE_FILE_MACHINE_AM33",
    "IMAGE_FILE_MACHINE_AMD64",
    "IMAGE_FILE_MACHINE_ARM",
    "IMAGE_FILE_MACHINE_ARM64",
    "IMAGE_FILE_MACHINE_ARM64EC",
    "IMAGE_FILE_MACHINE_ARM64X",
    "IMAGE_FILE_MACHINE_ARMNT",
    "IMAGE_FILE_MACHINE_AXP64",
    "IMAGE_FILE_MACHINE_EBC",
    "IMAGE_FILE_MACHINE_I386",
    "IMAGE_FILE_MACHINE_IA64",
    "IMAGE_FILE_MACHINE_LOONGARCH32",
    "IMAGE_FILE_MACHINE_LOONGARCH64",
    "IMAGE_FILE_MACHINE_M32R",
    "IMAGE_FILE_MACHINE_MIPS16",
    "IMAGE_FILE_RELOCS_STRIPPED",
    "IMAGE_FILE_EXECUTABLE_IMAGE",
    "IMAGE_FILE_LINE_NUMS_STRIPPED",
    "IMAGE_FILE_LOCAL_SYMS_STRIPPED",
    "IMAGE_FILE_AGGRESSIVE_WS_TRIM",
    "IMAGE_FILE_LARGE_ADDRESS_AWARE",
    "IMAGE_FILE_BYTES_REVERSED_LO",
    "IMAGE_FILE_32BIT_MACHINE",
    "IMAGE_FILE_DEBUG_STRIPPED",
    "IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP",
    "IMAGE_FILE_NET_RUN_FROM_SWAP",
    "IMAGE_FILE_SYSTEM",
    "IMAGE_FILE_DLL",
    "IMAGE_FILE_UP_SYSTEM_ONLY",
    "IMAGE_FILE_BYTES_REVERSED_HI",
    "IMAGE_SCN_CNT_CODE",
    "IMAGE_SCN_CNT_INITIALIZED_DATA",
    "IMAGE_SCN_CNT_UNINITIALIZED_DATA",
    "IMAGE_SCN_MEM_EXECUTE",
    "IMAGE_SCN_MEM_READ",
    "IMAGE_SCN_MEM_WRITE",
    "IMAGE_SYM_CLASS_EXTERNAL",
    "IMAGE_SYM_CLASS_STATIC",
    "decode_characteristics",
]
